export type DictationDifficulty = "easy" | "medium" | "hard";

export type DictationRoundNum = 1 | 2 | 3 | 4 | 5;

/** One dictation exam row (set 1–40 per level). */
export interface DictationItem {
  id: string;
  round: DictationRoundNum;
  difficulty: DictationDifficulty;
  setNumber: number;
  audioPath: string;
  /** Preferred playback audio generated by Gemini TTS (base64). */
  audioBase64?: string;
  /** MIME type for audioBase64 (e.g. audio/wav). */
  audioMimeType?: string;
  /** True when preferred audio is stored in IndexedDB for this item. */
  audioInIndexedDb?: boolean;
  transcript: string;
  hintText: string;
}

export interface DictationProgressRecord {
  bestScore: number;
  maxScore: number;
  lastScore: number;
  updatedAt: string;
}

export type DictationFullBank = Record<DictationRoundNum, Record<DictationDifficulty, DictationItem[]>>;
