// GENERATED by scripts/build-question-sets.ts — do not edit by hand.
// Re-run that script after changing the curriculum or the content banks.
//
// Fixed question sets: every exercise maps to specific item ids, in order.
// Nothing is randomised, so two learners at the same level answer the same
// questions and their scores mean the same thing.

/** Exercise key -> the exact item ids that exercise runs, in order. */
export const QUESTION_SETS: Record<string, string[]> = {
  "gr-tenses": [
    "tn-1",
    "tn-2",
    "tn-3",
    "tn-4",
    "tn-5",
    "tn-6",
    "tn-7",
    "tn-8"
  ],
  "gr-present": [
    "sp-pat-1",
    "sp-pat-2",
    "sp-pat-3",
    "sp-pat-4"
  ],
  "gr-complex": [
    "cx-1",
    "cx-2",
    "cx-3",
    "cx-4",
    "cx-5",
    "cx-6",
    "cx-7",
    "cj-1",
    "cj-2",
    "cj-3",
    "cj-10"
  ],
  "gr-sub": [
    "cj-4",
    "cj-5",
    "cj-6",
    "cj-7",
    "cj-8",
    "cj-9",
    "cj-11",
    "cj-12",
    "cj-13",
    "cj-14",
    "cj-15",
    "cj-16"
  ],
  "gr-relative": [
    "rel-1",
    "rel-2",
    "rel-3",
    "rel-4",
    "rel-5",
    "rel-6",
    "rel-7",
    "rel-8",
    "rel-9"
  ],
  "gr-reduction": [
    "rel-10",
    "rel-11",
    "rel-12",
    "rel-14",
    "rel-13"
  ],
  "wp-pattern": [
    "pt-1",
    "pt-2",
    "pt-3",
    "pt-4",
    "pt-5",
    "pt-6"
  ],
  "sp-people": [
    "sp-e1-1"
  ],
  "sp-objects": [
    "sp-e1-2"
  ],
  "sp-places": [
    "sp-e1-3"
  ],
  "dic-easy": [
    "e1-1",
    "e1-2",
    "e1-3",
    "e1-4",
    "e1-5"
  ],
  "dic-medium": [
    "e1-6",
    "e1-7",
    "e1-8",
    "e1-9",
    "e1-10"
  ],
  "wt-ws1": [
    "rw-e1-1"
  ],
  "wt-ws2": [
    "rw-e1-2"
  ],
  "wt-ws3": [
    "rw-e1-3"
  ],
  "wt-real1": [
    "arg-topic-1"
  ],
  "wt-real2": [
    "arg-topic-4"
  ],
  "wt-real3": [
    "arg-topic-7"
  ],
  "st-ls1": [
    "rs-e1-1"
  ],
  "st-ls2": [
    "rs-e1-2"
  ],
  "st-ls3": [
    "rs-e1-3"
  ],
  "st-real1": [
    "rs-topic-1::rs-topic-1-q1::1"
  ],
  "st-real2": [
    "rs-topic-1::rs-topic-1-q2::1"
  ],
  "st-real3": [
    "rs-topic-2::rs-topic-2-q1::1"
  ],
  "is-real": [
    "is-office-morning",
    "is-group-project",
    "is-class-presentation",
    "is-busy-schedule"
  ],
  "ic-set": [
    "1:easy:1",
    "1:easy:2",
    "1:easy:3"
  ],
  "ds-set": [
    "ds-r1-easy-s01",
    "ds-r1-easy-s02",
    "ds-r1-easy-s03"
  ],
  "rw-ladder": [
    "rwl-e1-1",
    "rwl-e1-2",
    "rwl-e1-3",
    "rwl-e1-4",
    "rwl-e1-5"
  ],
  "ct-easy": [
    "pt-e1",
    "pt-e2",
    "pt-e3",
    "pa-e1",
    "pa-e2",
    "pa-e3",
    "ad-e1",
    "ad-e2",
    "ad-e3",
    "tr-e1"
  ],
  "rs-exam": [
    "1:easy:1:1",
    "1:easy:1:2",
    "1:easy:1:3",
    "1:easy:1:4",
    "1:easy:1:5"
  ],
  "rv-exam": [
    "1:1:easy:1",
    "1:1:easy:2",
    "1:1:easy:3",
    "1:1:easy:4",
    "1:1:easy:5"
  ],
  "mgr-tenses": [
    "tn-1",
    "tn-2",
    "tn-3",
    "tn-4",
    "tn-5",
    "tn-6",
    "tn-7",
    "tn-8"
  ],
  "mgr-present": [
    "sp-pat-1",
    "sp-pat-2",
    "sp-pat-3",
    "sp-pat-4"
  ],
  "mgr-complex": [
    "cx-1",
    "cx-2",
    "cx-3",
    "cx-4",
    "cx-5",
    "cx-6",
    "cx-7",
    "cj-1",
    "cj-2",
    "cj-3",
    "cj-10"
  ],
  "mgr-sub": [
    "cj-4",
    "cj-5",
    "cj-6",
    "cj-7",
    "cj-8",
    "cj-9",
    "cj-11",
    "cj-12",
    "cj-13",
    "cj-14",
    "cj-15",
    "cj-16"
  ],
  "mgr-relative": [
    "rel-1",
    "rel-2",
    "rel-3",
    "rel-4",
    "rel-5",
    "rel-6",
    "rel-7",
    "rel-8",
    "rel-9"
  ],
  "mgr-reduction": [
    "rel-10",
    "rel-11",
    "rel-12",
    "rel-14",
    "rel-13"
  ],
  "mdic-easy": [
    "m1-1",
    "m1-2",
    "m1-3",
    "m1-4",
    "m1-5"
  ],
  "mdic-medium": [
    "m1-6",
    "m1-7",
    "m1-8",
    "m1-9",
    "m1-10"
  ],
  "mdic-hard": [
    "m1-11",
    "m1-12",
    "m1-13",
    "m1-14",
    "m1-15"
  ],
  "mwp-pattern": [
    "pt-1",
    "pt-2",
    "pt-3",
    "pt-4",
    "pt-5",
    "pt-6"
  ],
  "mwp-people": [
    "e79e13b9-a2b8-45b5-ac7d-227892cefc29"
  ],
  "mwp-objects": [
    "053a66b4-f088-44cb-9f1c-a35b7cb2e49c"
  ],
  "mwp-places": [
    "720c3ae3-e2e3-4e7b-9a6f-0905dd4e68cd"
  ],
  "msp-people": [
    "f34b31e6-2cc1-4f5a-a0fd-a12f4f103995"
  ],
  "msp-objects": [
    "39a36df6-2240-4412-8403-6c57a579a25c"
  ],
  "msp-places": [
    "ec6b394c-6dcb-4344-905b-784ea551ecb0"
  ],
  "mwt-ws1": [
    "rw-m1-1"
  ],
  "mwt-ws2": [
    "rw-m1-2"
  ],
  "mwt-ws3": [
    "rw-m1-3"
  ],
  "mwt-real1": [
    "arg-topic-3"
  ],
  "mwt-real2": [
    "arg-topic-6"
  ],
  "mwt-real3": [
    "arg-topic-9"
  ],
  "mst-ls1": [
    "rs-m1-1"
  ],
  "mst-ls2": [
    "rs-m1-2"
  ],
  "mst-ls3": [
    "rs-m1-3"
  ],
  "mst-real1": [
    "rs-r3-01::rs-r3-01-q1::3"
  ],
  "mst-real2": [
    "rs-r3-01::rs-r3-01-q2::3"
  ],
  "mst-real3": [
    "rs-r3-02::rs-r3-02-q1::3"
  ],
  "mis-real": [
    "is-help-from-teacher",
    "is-campus-place",
    "is-free-time-habit",
    "is-solving-problem"
  ],
  "mic-set": [
    "3:easy:25",
    "3:easy:26",
    "3:easy:27"
  ],
  "mds-set": [
    "ds-r1-medium-s11",
    "ds-r1-medium-s12",
    "ds-r1-medium-s13"
  ],
  "mrw-ladder": [
    "rwl-m1-1",
    "rwl-m1-2",
    "rwl-m1-3",
    "rwl-m1-4",
    "rwl-m1-5"
  ],
  "mrw-hard": [
    "rwl-m1-6",
    "rwl-m1-7",
    "rwl-m1-8"
  ],
  "mct": [
    "pt-m1",
    "pt-m2",
    "pt-m3",
    "pt-m4",
    "pa-m1",
    "pa-m2",
    "pa-m3",
    "pa-m4",
    "ad-m1",
    "ad-m2"
  ],
  "mrs-exam": [
    "1:easy:1:1",
    "1:easy:1:2",
    "1:medium:1:1",
    "1:medium:1:2",
    "1:medium:1:3"
  ],
  "mrv-exam": [
    "1:1:easy:1",
    "1:1:easy:2",
    "1:1:medium:1",
    "1:1:medium:2",
    "1:1:medium:3"
  ],
  "hgr-tenses": [
    "tn-1",
    "tn-2",
    "tn-3",
    "tn-4",
    "tn-5",
    "tn-6",
    "tn-7",
    "tn-8"
  ],
  "hgr-present": [
    "sp-pat-1",
    "sp-pat-2",
    "sp-pat-3",
    "sp-pat-4"
  ],
  "hgr-complex": [
    "cx-1",
    "cx-2",
    "cx-3",
    "cx-4",
    "cx-5",
    "cx-6",
    "cx-7",
    "cj-1",
    "cj-2",
    "cj-3",
    "cj-10"
  ],
  "hgr-sub": [
    "cj-4",
    "cj-5",
    "cj-6",
    "cj-7",
    "cj-8",
    "cj-9",
    "cj-11",
    "cj-12",
    "cj-13",
    "cj-14",
    "cj-15",
    "cj-16"
  ],
  "hgr-relative": [
    "rel-1",
    "rel-2",
    "rel-3",
    "rel-4",
    "rel-5",
    "rel-6",
    "rel-7",
    "rel-8",
    "rel-9"
  ],
  "hgr-reduction": [
    "rel-10",
    "rel-11",
    "rel-12",
    "rel-14",
    "rel-13"
  ],
  "hdic-easy": [
    "a1-1",
    "a1-2",
    "a1-3",
    "a1-4",
    "a1-5"
  ],
  "hdic-medium": [
    "a1-6",
    "a1-7",
    "a1-8",
    "a1-9",
    "a1-10"
  ],
  "hdic-hard": [
    "a1-11",
    "a1-12",
    "a1-13",
    "a1-14",
    "a1-15"
  ],
  "hdic-advanced": [
    "a1-16",
    "a1-17",
    "a1-18",
    "a1-19",
    "a1-20",
    "a2-1"
  ],
  "hwp-pattern": [
    "pt-1",
    "pt-2",
    "pt-3",
    "pt-4",
    "pt-5",
    "pt-6"
  ],
  "hwp-people": [
    "fe6168d5-dbb3-44c0-8819-64628fd1c501"
  ],
  "hwp-objects": [
    "4c9a0c50-34bc-4e32-ae45-66d8492dc209"
  ],
  "hwp-places": [
    "7fe0090c-bcaa-422a-afc9-06c12ddbf77f"
  ],
  "hsp-people": [
    "3d0c9f12-8221-4380-b612-76d0a3c334da"
  ],
  "hsp-objects": [
    "84ea58b4-6ce5-431c-a94a-a7f0006ccc04"
  ],
  "hsp-places": [
    "ed1fcfaf-617c-4d22-be6e-ae5271871c12"
  ],
  "hwt-ws1": [
    "rw-a1-1"
  ],
  "hwt-ws2": [
    "rw-a1-2"
  ],
  "hwt-ws3": [
    "rw-a1-3"
  ],
  "hwt-real1": [
    "arg-topic-2"
  ],
  "hwt-real2": [
    "arg-topic-5"
  ],
  "hwt-real3": [
    "arg-topic-8"
  ],
  "hst-ls1": [
    "rs-a1-1"
  ],
  "hst-ls2": [
    "rs-a1-2"
  ],
  "hst-ls3": [
    "rs-a1-3"
  ],
  "hst-real1": [
    "rs-r5-01::rs-r5-01-q1::5"
  ],
  "hst-real2": [
    "rs-r5-01::rs-r5-01-q2::5"
  ],
  "hst-real3": [
    "rs-r5-02::rs-r5-02-q1::5"
  ],
  "his-real": [
    "is-learning-new-skill",
    "is-future-plan",
    "is-study-break",
    "is-late-arrival"
  ],
  "hic-set": [
    "5:easy:34",
    "5:easy:35",
    "5:easy:36"
  ],
  "hds-set": [
    "ds-r1-hard-s16",
    "ds-r1-hard-s17",
    "ds-r1-hard-s18"
  ],
  "hrw-ladder": [
    "rwl-a1-1",
    "rwl-a1-2",
    "rwl-a1-3",
    "rwl-a1-4",
    "rwl-a1-5"
  ],
  "hrw-hard": [
    "rwl-a1-6",
    "rwl-a1-7",
    "rwl-a1-8"
  ],
  "hct": [
    "pt-h1",
    "pt-h2",
    "pt-h3",
    "pa-h1",
    "pa-h2",
    "pa-h3",
    "ad-h1",
    "ad-h2",
    "ad-h3",
    "tr-h1"
  ],
  "hrs-exam": [
    "1:medium:1:1",
    "1:medium:1:2",
    "1:hard:1:1",
    "1:hard:1:2",
    "1:hard:1:3"
  ],
  "hrv-exam": [
    "1:1:medium:1",
    "1:1:medium:2",
    "1:1:hard:1",
    "1:1:hard:2",
    "1:1:hard:3"
  ]
};

/** Exercises with no items yet — see the build log for why. */
export const UNFILLED_EXERCISES: string[] = [];

export function questionsFor(exerciseKey: string): string[] {
  return QUESTION_SETS[exerciseKey] ?? [];
}
