// GENERATED by scripts/build-question-sets.ts — do not edit by hand.
// Re-run that script after changing the curriculum or the content banks.
//
// Fixed question sets: every exercise maps to specific item ids, in order.
// Nothing is randomised, so two learners at the same level answer the same
// questions and their scores mean the same thing.

/** Exercise key -> the exact item ids that exercise runs, in order. */
export const QUESTION_SETS: Record<string, string[]> = {
  "gr-conj": [
    "cj-1",
    "cj-2",
    "cj-3",
    "cj-4",
    "cj-5",
    "cj-6",
    "cj-7",
    "cj-8",
    "cj-9",
    "cj-10"
  ],
  "gr-present": [
    "sp-pat-1",
    "sp-pat-2",
    "sp-pat-3",
    "sp-pat-4"
  ],
  "gr-runon": [
    "ro-1",
    "ro-2",
    "ro-3",
    "ro-4",
    "ro-5",
    "ro-6",
    "ro-7"
  ],
  "gr-transition": [
    "tr-1",
    "tr-2",
    "tr-3",
    "tr-4",
    "tr-5",
    "tr-6",
    "tr-7"
  ],
  "gr-tense": [
    "pa-e1",
    "pa-e2",
    "pa-e3",
    "pa-e4",
    "pa-e5",
    "pa-e6",
    "pa-e7",
    "pa-e8",
    "pa-e9",
    "pa-e10"
  ],
  "gr-relative": [
    "rel-1",
    "rel-2",
    "rel-3",
    "rel-4",
    "rel-5",
    "rel-6",
    "rel-7"
  ],
  "dic-easy": [
    "e1-1",
    "e1-2",
    "e1-3",
    "e1-4",
    "e1-5"
  ],
  "dic-medium": [
    "e1-6",
    "e1-7",
    "e1-8",
    "e1-9",
    "e1-10"
  ],
  "wt-real": [
    "rw-e1-1",
    "rw-e1-2",
    "rw-e1-3",
    "rw-e1-4"
  ],
  "st-real": [
    "rs-e1-1",
    "rs-e1-2",
    "rs-e1-3",
    "rs-e1-4"
  ],
  "is-real": [],
  "ic-set": [],
  "rw-ladder": [
    "rwl-e1-1",
    "rwl-e1-2",
    "rwl-e1-3",
    "rwl-e1-4",
    "rwl-e1-5"
  ],
  "ct-easy": [
    "pt-e1",
    "pt-e2",
    "pt-e3",
    "pa-e1",
    "pa-e2",
    "pa-e3",
    "ad-e1",
    "ad-e2",
    "ad-e3",
    "tr-e1"
  ],
  "rs-exam": [
    "mi-02",
    "mi-03",
    "mi-05",
    "mi-06",
    "mi-08"
  ],
  "rv-exam": [
    "cv-1",
    "cv-2",
    "cv-3",
    "cv-4",
    "cv-5"
  ],
  "mgr-conj": [
    "cj-1",
    "cj-2",
    "cj-3",
    "cj-4",
    "cj-5",
    "cj-6",
    "cj-7",
    "cj-8",
    "cj-9",
    "cj-10"
  ],
  "mgr-present": [
    "sp-pat-1",
    "sp-pat-2",
    "sp-pat-3",
    "sp-pat-4"
  ],
  "mgr-runon": [
    "ro-1",
    "ro-2",
    "ro-3",
    "ro-4",
    "ro-5",
    "ro-6",
    "ro-7"
  ],
  "mgr-transition": [
    "tr-1",
    "tr-2",
    "tr-3",
    "tr-4",
    "tr-5",
    "tr-6",
    "tr-7"
  ],
  "mgr-tense": [
    "pa-m1",
    "pa-m2",
    "pa-m3",
    "pa-m4",
    "pa-m5",
    "pa-m6",
    "pa-m7",
    "pa-m8",
    "pa-m9",
    "pa-m10"
  ],
  "mgr-relative": [
    "rel-1",
    "rel-2",
    "rel-3",
    "rel-4",
    "rel-5",
    "rel-6",
    "rel-7"
  ],
  "mdic-easy": [
    "m1-1",
    "m1-2",
    "m1-3",
    "m1-4",
    "m1-5"
  ],
  "mdic-medium": [
    "m1-6",
    "m1-7",
    "m1-8",
    "m1-9",
    "m1-10"
  ],
  "mdic-hard": [
    "m1-11",
    "m1-12",
    "m1-13",
    "m1-14",
    "m1-15"
  ],
  "mwp-people": [
    "e79e13b9-a2b8-45b5-ac7d-227892cefc29"
  ],
  "mwp-objects": [
    "053a66b4-f088-44cb-9f1c-a35b7cb2e49c"
  ],
  "mwp-places": [
    "720c3ae3-e2e3-4e7b-9a6f-0905dd4e68cd"
  ],
  "msp-people": [
    "f34b31e6-2cc1-4f5a-a0fd-a12f4f103995"
  ],
  "msp-objects": [
    "39a36df6-2240-4412-8403-6c57a579a25c"
  ],
  "msp-places": [
    "ec6b394c-6dcb-4344-905b-784ea551ecb0"
  ],
  "mwt-real": [
    "arg-topic-3",
    "arg-topic-6",
    "arg-topic-9",
    "arg-topic-12"
  ],
  "mst-real": [
    "rs-r3-01::rs-r3-01-q1::3",
    "rs-r3-01::rs-r3-01-q2::3",
    "rs-r3-02::rs-r3-02-q1::3",
    "rs-r3-02::rs-r3-02-q2::3"
  ],
  "mis-real": [],
  "mic-set": [],
  "mrw-ladder": [
    "rwl-m1-1",
    "rwl-m1-2",
    "rwl-m1-3",
    "rwl-m1-4",
    "rwl-m1-5"
  ],
  "mrw-hard": [
    "rwl-m1-6",
    "rwl-m1-7",
    "rwl-m1-8"
  ],
  "mct": [
    "pt-m1",
    "pt-m2",
    "pt-m3",
    "pt-m4",
    "pa-m1",
    "pa-m2",
    "pa-m3",
    "pa-m4",
    "ad-m1",
    "ad-m2"
  ],
  "mrs-exam": [
    "mi-01",
    "mi-04",
    "mi-07",
    "mi-09",
    "mi-10"
  ],
  "mrv-exam": [
    "cv-1",
    "cv-2",
    "cv-3",
    "cv-4",
    "cv-5"
  ],
  "hgr-conj": [
    "cj-1",
    "cj-2",
    "cj-3",
    "cj-4",
    "cj-5",
    "cj-6",
    "cj-7",
    "cj-8",
    "cj-9",
    "cj-10"
  ],
  "hgr-present": [
    "sp-pat-1",
    "sp-pat-2",
    "sp-pat-3",
    "sp-pat-4"
  ],
  "hgr-runon": [
    "ro-1",
    "ro-2",
    "ro-3",
    "ro-4",
    "ro-5",
    "ro-6",
    "ro-7"
  ],
  "hgr-transition": [
    "tr-1",
    "tr-2",
    "tr-3",
    "tr-4",
    "tr-5",
    "tr-6",
    "tr-7"
  ],
  "hgr-tense": [
    "pa-h1",
    "pa-h2",
    "pa-h3",
    "pa-h4",
    "pa-h5",
    "pa-h6",
    "pa-h7",
    "pa-h8",
    "pa-h9",
    "pa-h10"
  ],
  "hgr-relative": [
    "rel-1",
    "rel-2",
    "rel-3",
    "rel-4",
    "rel-5",
    "rel-6",
    "rel-7"
  ],
  "hdic-easy": [
    "a1-1",
    "a1-2",
    "a1-3",
    "a1-4",
    "a1-5"
  ],
  "hdic-medium": [
    "a1-6",
    "a1-7",
    "a1-8",
    "a1-9",
    "a1-10"
  ],
  "hdic-hard": [
    "a1-11",
    "a1-12",
    "a1-13",
    "a1-14",
    "a1-15"
  ],
  "hdic-advanced": [
    "a1-16",
    "a1-17",
    "a1-18",
    "a1-19",
    "a1-20",
    "a2-1"
  ],
  "hwp-people": [
    "fe6168d5-dbb3-44c0-8819-64628fd1c501"
  ],
  "hwp-objects": [
    "4c9a0c50-34bc-4e32-ae45-66d8492dc209"
  ],
  "hwp-places": [
    "7fe0090c-bcaa-422a-afc9-06c12ddbf77f"
  ],
  "hsp-people": [
    "3d0c9f12-8221-4380-b612-76d0a3c334da"
  ],
  "hsp-objects": [
    "84ea58b4-6ce5-431c-a94a-a7f0006ccc04"
  ],
  "hsp-places": [
    "ed1fcfaf-617c-4d22-be6e-ae5271871c12"
  ],
  "hwt-real": [
    "arg-topic-2",
    "arg-topic-5",
    "arg-topic-8",
    "arg-topic-11"
  ],
  "hst-real": [
    "rs-r5-01::rs-r5-01-q1::5",
    "rs-r5-01::rs-r5-01-q2::5",
    "rs-r5-02::rs-r5-02-q1::5",
    "rs-r5-02::rs-r5-02-q2::5"
  ],
  "his-real": [],
  "hic-set": [],
  "hrw-ladder": [
    "rwl-a1-1",
    "rwl-a1-2",
    "rwl-a1-3",
    "rwl-a1-4",
    "rwl-a1-5"
  ],
  "hrw-hard": [
    "rwl-a1-6",
    "rwl-a1-7",
    "rwl-a1-8"
  ],
  "hct": [
    "pt-h1",
    "pt-h2",
    "pt-h3",
    "pa-h1",
    "pa-h2",
    "pa-h3",
    "ad-h1",
    "ad-h2",
    "ad-h3",
    "tr-h1"
  ],
  "hrs-exam": [
    "mi-61",
    "mi-62",
    "mi-63",
    "mi-64",
    "mi-65"
  ],
  "hrv-exam": [
    "cv-1",
    "cv-2",
    "cv-3",
    "cv-4",
    "cv-5"
  ]
};

/** Exercises with no items yet — see the build log for why. */
export const UNFILLED_EXERCISES: string[] = [
  "is-real",
  "ic-set",
  "mis-real",
  "mic-set",
  "his-real",
  "hic-set"
];

export function questionsFor(exerciseKey: string): string[] {
  return QUESTION_SETS[exerciseKey] ?? [];
}
