// GENERATED by scripts/build-question-sets.ts — do not edit by hand.
// Re-run that script after changing the curriculum or the content banks.
//
// Fixed question sets: every exercise maps to specific item ids, in order.
// Nothing is randomised, so two learners at the same level answer the same
// questions and their scores mean the same thing.

/** Exercise key -> the exact item ids that exercise runs, in order. */
export const QUESTION_SETS: Record<string, string[]> = {
  "gr-conj": [],
  "gr-present": [
    "pt-e1",
    "pt-e2",
    "pt-e3",
    "pt-e4",
    "pt-e5",
    "pt-e6",
    "pt-e7",
    "pt-e8",
    "pt-e9",
    "pt-e10"
  ],
  "gr-runon": [],
  "gr-transition": [
    "tr-e1",
    "tr-e2",
    "tr-e3",
    "tr-e4",
    "tr-e5",
    "tr-e6",
    "tr-e7",
    "tr-e8",
    "tr-e9",
    "tr-e10"
  ],
  "gr-tense": [
    "pa-e1",
    "pa-e2",
    "pa-e3",
    "pa-e4",
    "pa-e5",
    "pa-e6",
    "pa-e7",
    "pa-e8",
    "pa-e9",
    "pa-e10"
  ],
  "gr-relative": [],
  "wp-people": [
    "wp-e1-1",
    "wp-e1-2",
    "wp-e1-3"
  ],
  "wp-objects": [
    "wp-e1-1",
    "wp-e1-2",
    "wp-e1-3"
  ],
  "wp-places": [
    "wp-e1-1",
    "wp-e1-2",
    "wp-e1-3"
  ],
  "sp-people": [
    "sp-e1-1",
    "sp-e1-2",
    "sp-e1-3"
  ],
  "sp-objects": [
    "sp-e1-1",
    "sp-e1-2",
    "sp-e1-3"
  ],
  "sp-places": [
    "sp-e1-1",
    "sp-e1-2",
    "sp-e1-3"
  ],
  "dic-easy": [
    "e1-1",
    "e1-2",
    "e1-3",
    "e1-4",
    "e1-5"
  ],
  "dic-medium": [
    "e1-1",
    "e1-2",
    "e1-3",
    "e1-4",
    "e1-5"
  ],
  "wt-real": [
    "rw-e1-1",
    "rw-e1-2",
    "rw-e1-3"
  ],
  "st-real": [
    "rs-e1-1",
    "rs-e1-2",
    "rs-e1-3"
  ],
  "is-real": [],
  "ic-set": [],
  "rw-ladder": [
    "rwl-e1-1",
    "rwl-e1-2",
    "rwl-e1-3",
    "rwl-e1-4",
    "rwl-e1-5"
  ],
  "ct-easy": [
    "pt-e1",
    "pt-e2",
    "pt-e3",
    "pa-e1",
    "pa-e2",
    "pa-e3",
    "ad-e1",
    "ad-e2",
    "ad-e3",
    "tr-e1"
  ],
  "rs-exam": [
    "mi-02",
    "mi-03",
    "mi-05",
    "mi-06",
    "mi-08"
  ],
  "rv-exam": [
    "cv-1",
    "cv-2",
    "cv-3",
    "cv-4",
    "cv-5"
  ],
  "mgr-conj": [],
  "mgr-present": [
    "pt-m1",
    "pt-m2",
    "pt-m3",
    "pt-m4",
    "pt-m5",
    "pt-m6",
    "pt-m7",
    "pt-m8",
    "pt-m9",
    "pt-m10"
  ],
  "mgr-runon": [],
  "mgr-transition": [
    "tr-m1",
    "tr-m2",
    "tr-m3",
    "tr-m4",
    "tr-m5",
    "tr-m6",
    "tr-m7",
    "tr-m8",
    "tr-m9",
    "tr-m10"
  ],
  "mgr-tense": [
    "pa-m1",
    "pa-m2",
    "pa-m3",
    "pa-m4",
    "pa-m5",
    "pa-m6",
    "pa-m7",
    "pa-m8",
    "pa-m9",
    "pa-m10"
  ],
  "mgr-relative": [],
  "mdic-easy": [
    "m1-1",
    "m1-2",
    "m1-3",
    "m1-4",
    "m1-5"
  ],
  "mdic-medium": [
    "m1-1",
    "m1-2",
    "m1-3",
    "m1-4",
    "m1-5"
  ],
  "mdic-hard": [
    "m1-1",
    "m1-2",
    "m1-3",
    "m1-4",
    "m1-5"
  ],
  "mwp-people": [
    "wp-m1-1",
    "wp-m1-2",
    "wp-m1-3"
  ],
  "mwp-objects": [
    "wp-m1-1",
    "wp-m1-2",
    "wp-m1-3"
  ],
  "mwp-places": [
    "wp-m1-1",
    "wp-m1-2",
    "wp-m1-3"
  ],
  "msp-people": [
    "sp-m1-1",
    "sp-m1-2",
    "sp-m1-3"
  ],
  "msp-objects": [
    "sp-m1-1",
    "sp-m1-2",
    "sp-m1-3"
  ],
  "msp-places": [
    "sp-m1-1",
    "sp-m1-2",
    "sp-m1-3"
  ],
  "mwt-real": [
    "rw-m1-1",
    "rw-m1-2",
    "rw-m1-3"
  ],
  "mst-real": [
    "rs-m1-1",
    "rs-m1-2",
    "rs-m1-3"
  ],
  "mis-real": [],
  "mic-set": [],
  "mrw-ladder": [
    "rwl-m1-1",
    "rwl-m1-2",
    "rwl-m1-3",
    "rwl-m1-4",
    "rwl-m1-5"
  ],
  "mrw-hard": [
    "rwl-m1-1",
    "rwl-m1-2",
    "rwl-m1-3"
  ],
  "mct": [
    "pt-m1",
    "pt-m2",
    "pt-m3",
    "pt-m4",
    "pa-m1",
    "pa-m2",
    "pa-m3",
    "pa-m4",
    "ad-m1",
    "ad-m2"
  ],
  "mrs-exam": [
    "mi-01",
    "mi-04",
    "mi-07",
    "mi-09",
    "mi-10"
  ],
  "mrv-exam": [
    "cv-1",
    "cv-2",
    "cv-3",
    "cv-4",
    "cv-5"
  ],
  "hgr-conj": [],
  "hgr-present": [
    "pt-h1",
    "pt-h2",
    "pt-h3",
    "pt-h4",
    "pt-h5",
    "pt-h6",
    "pt-h7",
    "pt-h8",
    "pt-h9",
    "pt-h10"
  ],
  "hgr-runon": [],
  "hgr-transition": [
    "tr-h1",
    "tr-h2",
    "tr-h3",
    "tr-h4",
    "tr-h5",
    "tr-h6",
    "tr-h7",
    "tr-h8",
    "tr-h9",
    "tr-h10"
  ],
  "hgr-tense": [
    "pa-h1",
    "pa-h2",
    "pa-h3",
    "pa-h4",
    "pa-h5",
    "pa-h6",
    "pa-h7",
    "pa-h8",
    "pa-h9",
    "pa-h10"
  ],
  "hgr-relative": [],
  "hdic-easy": [
    "a1-1",
    "a1-2",
    "a1-3",
    "a1-4",
    "a1-5"
  ],
  "hdic-medium": [
    "a1-1",
    "a1-2",
    "a1-3",
    "a1-4",
    "a1-5"
  ],
  "hdic-hard": [
    "a1-1",
    "a1-2",
    "a1-3",
    "a1-4",
    "a1-5"
  ],
  "hdic-advanced": [
    "a1-1",
    "a1-2",
    "a1-3",
    "a1-4",
    "a1-5",
    "a1-6"
  ],
  "hwp-people": [
    "wp-a1-1",
    "wp-a1-2",
    "wp-a1-3"
  ],
  "hwp-objects": [
    "wp-a1-1",
    "wp-a1-2",
    "wp-a1-3"
  ],
  "hwp-places": [
    "wp-a1-1",
    "wp-a1-2",
    "wp-a1-3"
  ],
  "hsp-people": [
    "sp-a1-1",
    "sp-a1-2",
    "sp-a1-3"
  ],
  "hsp-objects": [
    "sp-a1-1",
    "sp-a1-2",
    "sp-a1-3"
  ],
  "hsp-places": [
    "sp-a1-1",
    "sp-a1-2",
    "sp-a1-3"
  ],
  "hwt-real": [
    "rw-a1-1",
    "rw-a1-2",
    "rw-a1-3"
  ],
  "hst-real": [
    "rs-a1-1",
    "rs-a1-2",
    "rs-a1-3"
  ],
  "his-real": [],
  "hic-set": [],
  "hrw-ladder": [
    "rwl-a1-1",
    "rwl-a1-2",
    "rwl-a1-3",
    "rwl-a1-4",
    "rwl-a1-5"
  ],
  "hrw-hard": [
    "rwl-a1-1",
    "rwl-a1-2",
    "rwl-a1-3"
  ],
  "hct": [
    "pt-h1",
    "pt-h2",
    "pt-h3",
    "pa-h1",
    "pa-h2",
    "pa-h3",
    "ad-h1",
    "ad-h2",
    "ad-h3",
    "tr-h1"
  ],
  "hrs-exam": [
    "mi-61",
    "mi-62",
    "mi-63",
    "mi-64",
    "mi-65"
  ],
  "hrv-exam": [
    "cv-1",
    "cv-2",
    "cv-3",
    "cv-4",
    "cv-5"
  ]
};

/** Exercises with no items yet — see the build log for why. */
export const UNFILLED_EXERCISES: string[] = [
  "gr-conj",
  "gr-runon",
  "gr-relative",
  "is-real",
  "ic-set",
  "mgr-conj",
  "mgr-runon",
  "mgr-relative",
  "mis-real",
  "mic-set",
  "hgr-conj",
  "hgr-runon",
  "hgr-relative",
  "his-real",
  "hic-set"
];

export function questionsFor(exerciseKey: string): string[] {
  return QUESTION_SETS[exerciseKey] ?? [];
}
