/**
 * AUTO-GENERATED by scripts/build-mini-study-audio.ts
 * Do not edit by hand. Run `npm run build:audio` to regenerate.
 *
 * Each entry is a 16-char hex hash of an English text used in Mini Study
 * listening phases. A corresponding MP3 lives at
 * `public/mini-study-audio/<hash>.mp3`.
 */

export const MINI_STUDY_AUDIO_HASHES: ReadonlySet<string> = new Set<string>([
  "07531981432c9043",
  "0aba91921203a312",
  "1195213fa75fd306",
  "14748ced0f784f73",
  "1df1109d0eb01fca",
  "2224f1c676e5e820",
  "2a11578f83903630",
  "2c23c8c01d216648",
  "32764568d080b060",
  "399baca885f238fa",
  "4bb560038999a185",
  "56fda24df8fd808c",
  "5813cff6931432e2",
  "5d8eeca37496a158",
  "67b4cb32accbae48",
  "85d6ee3cb301daaf",
  "8bb9edc38d1c7bdc",
  "8f7f4c52f931e002",
  "967400eaa9919066",
  "9d2b94c2291956eb",
  "a28909df2b14be78",
  "a49e48cf10f492eb",
  "a56e57fddcec8fa0",
  "a78f8aeca9cdc86c",
  "ae43a0c7f0be8561",
  "b06d39e3df8e841e",
  "b60de0b16fdde5e4",
  "be45897bdff6221e",
  "c941a83f97682207",
  "cbd28d575a7763ca",
  "d285f3182284273e",
  "daaf4639f1aa960d",
  "dd26e554afcab755",
  "e15d1ed972e861e4",
  "e38c7587e2690e81",
  "ea24249d3ebba3fb",
  "efa30dbccb227be6",
  "f0f6caa4dfeda87b",
  "f2afd34b5fd17d20",
  "fab3bfe62d9ca2f2",
]);
