#!/usr/bin/env tsx
/**
 * Pre-generate Deepgram TTS audio for every Mini Study listening text.
 *
 * Run once after content changes:
 *   npm run build:audio
 *
 * Reads DEEPGRAM_API_KEY from .env.local.
 *
 * For each text used by a listening phase (dictation sentences, scenarios,
 * listen-respond audioText), it:
 *   1. Computes sha256(trim(text))[:16] as the canonical hash
 *   2. Checks if public/mini-study-audio/<hash>.mp3 already exists — skip if yes
 *   3. Otherwise calls Deepgram TTS, writes the MP3
 *   4. Updates src/lib/mini-study/audio-manifest.ts with the full hash set
 *
 * Idempotent: re-running only generates missing files.
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { MINI_STUDY_SESSIONS } from "../src/lib/mini-study/content";

function loadEnv() {
  try {
    const raw = readFileSync(join(process.cwd(), ".env.local"), "utf8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (!m) continue;
      const key = m[1];
      let val = m[2];
      if (val.startsWith('"') && val.endsWith('"')) val = val.slice(1, -1);
      if (!process.env[key]) process.env[key] = val;
    }
  } catch {
    /* ignore */
  }
}
loadEnv();

const DEEPGRAM_KEY = process.env.DEEPGRAM_API_KEY?.trim();
if (!DEEPGRAM_KEY) {
  console.error("DEEPGRAM_API_KEY not set in .env.local");
  process.exit(1);
}

const MODEL = process.env.DEEPGRAM_TTS_MODEL?.trim() || "aura-2-thalia-en";
const OUT_DIR = join(process.cwd(), "public", "mini-study-audio");
const MANIFEST_PATH = join(
  process.cwd(),
  "src",
  "lib",
  "mini-study",
  "audio-manifest.ts",
);

function hashText(text: string): string {
  return createHash("sha256")
    .update(text.trim(), "utf8")
    .digest("hex")
    .slice(0, 16);
}

/** Collect every English text that a listening phase will play. */
function collectTexts(): { text: string; sourceLabel: string }[] {
  const out: { text: string; sourceLabel: string }[] = [];
  const seen = new Set<string>();
  for (const s of MINI_STUDY_SESSIONS) {
    if (s.kind === "dictation") {
      for (const it of s.items) {
        if (!seen.has(it.sentence)) {
          seen.add(it.sentence);
          out.push({ text: it.sentence, sourceLabel: `${s.id}/${it.id}` });
        }
      }
    } else if (s.kind === "interactive-listening-mc") {
      for (const sc of s.scenarios) {
        if (!seen.has(sc.scenarioText)) {
          seen.add(sc.scenarioText);
          out.push({ text: sc.scenarioText, sourceLabel: `${s.id}/${sc.id}` });
        }
      }
    } else if (s.kind === "listen-respond") {
      for (const ex of s.exercises) {
        if (!seen.has(ex.audioText)) {
          seen.add(ex.audioText);
          out.push({ text: ex.audioText, sourceLabel: `${s.id}/${ex.id}` });
        }
      }
    }
  }
  return out;
}

async function synthesize(text: string): Promise<Buffer> {
  const url = `https://api.deepgram.com/v1/speak?model=${encodeURIComponent(MODEL)}`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Token ${DEEPGRAM_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ text: text.trim() }),
  });
  if (!res.ok) {
    const msg = (await res.text().catch(() => "")) || `status ${res.status}`;
    throw new Error(`Deepgram error: ${msg}`);
  }
  const ab = await res.arrayBuffer();
  const buf = Buffer.from(ab);
  if (buf.length === 0) throw new Error("Deepgram returned empty audio");
  return buf;
}

function writeManifest(hashes: string[]) {
  const sorted = [...new Set(hashes)].sort();
  const body =
    "/**\n" +
    " * AUTO-GENERATED by scripts/build-mini-study-audio.ts\n" +
    " * Do not edit by hand. Run `npm run build:audio` to regenerate.\n" +
    " *\n" +
    " * Each entry is a 16-char hex hash of an English text used in Mini Study\n" +
    " * listening phases. A corresponding MP3 lives at\n" +
    " * `public/mini-study-audio/<hash>.mp3`.\n" +
    " */\n\n" +
    "export const MINI_STUDY_AUDIO_HASHES: ReadonlySet<string> = new Set<string>([\n" +
    sorted.map((h) => `  "${h}",`).join("\n") +
    "\n]);\n";
  writeFileSync(MANIFEST_PATH, body, "utf8");
}

async function main() {
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  const texts = collectTexts();
  console.log(`Found ${texts.length} unique texts to bake`);

  const allHashes: string[] = [];
  let generated = 0;
  let skipped = 0;
  let failed = 0;

  for (let i = 0; i < texts.length; i++) {
    const { text, sourceLabel } = texts[i];
    const hash = hashText(text);
    allHashes.push(hash);
    const outPath = join(OUT_DIR, `${hash}.mp3`);
    if (existsSync(outPath)) {
      skipped++;
      continue;
    }
    const preview = text.replace(/\s+/g, " ").slice(0, 60);
    process.stdout.write(
      `[${i + 1}/${texts.length}] ${sourceLabel}  ${preview}…  `,
    );
    try {
      const buf = await synthesize(text);
      writeFileSync(outPath, buf);
      generated++;
      process.stdout.write(`✓ (${(buf.length / 1024).toFixed(0)}kb)\n`);
    } catch (e) {
      failed++;
      const msg = e instanceof Error ? e.message : String(e);
      process.stdout.write(`✗ ${msg.slice(0, 100)}\n`);
    }
  }

  writeManifest(allHashes);

  console.log(
    `\nDone — generated ${generated}, skipped ${skipped}, failed ${failed}. Manifest: ${allHashes.length} entries.`,
  );
  if (failed > 0) process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
