import type { CampusListeningScenario } from "./campus-listening-types";

/**
 * Mobile-only บทเรียน: campus listening with prefix-hint FITB follow-ups.
 * Twenty college scenarios (professor ↔ student / classmates).
 */
export const CAMPUS_LISTENING_SCENARIOS: CampusListeningScenario[] = [
  {
    id: "01",
    titleTh: "ขอเรียนออนไลน์แทน",
    titleEn: "Online attendance request",
    scenarioEn:
      "You are a psychology major who missed several lectures because of a family emergency. You ask your professor if you can follow the course online and still pass without regular attendance.",
    keywords: ["psychology", "attendance", "professor"],
    questions: [
      {
        promptEn: "You are a ___ major student.",
        correctWord: "psychology",
        prefixLength: 3,
        coachTh: "ข้อแรก: ฟังว่าเขาเรียนสาขาอะไร แล้วเติมคำที่ขึ้นต้นด้วย psy",
        coachEn: "Question 1: What is the student's major? Fill in the word starting with psy.",
        explanationTh: "psychology = จิตวิทยา (สาขาวิชา)",
        explanationEn: "psychology = the academic major (psychology department).",
      },
      {
        promptEn: "You missed class because of a family ___.",
        correctWord: "emergency",
        prefixLength: 2,
        coachTh: "ข้อสอง: เหตุผลที่ขาดเรียนคืออะไร? คำขึ้นต้น em",
        coachEn: "Question 2: Why did they miss class? Word starts with em.",
        explanationTh: "emergency = เหตุฉุกเฉินในครอบครัว",
        explanationEn: "emergency = an urgent family situation.",
      },
      {
        promptEn: "You ask to pass without regular ___.",
        correctWord: "attendance",
        prefixLength: 3,
        coachTh: "ข้อสาม: เขาอยากยกเว้นอะไร? คำขึ้นต้น att",
        coachEn: "Question 3: What do they want waived? Starts with att.",
        explanationTh: "attendance = การเข้าเรียน / การเช็คชื่อ",
        explanationEn: "attendance = physically coming to class.",
      },
    ],
  },
  {
    id: "02",
    titleTh: "จดหมายแนะนำตัว",
    titleEn: "Recommendation letter",
    scenarioEn:
      "Your classmate asks you to write a recommendation letter before the graduate school deadline. You meet your professor during office hours to confirm what details to include.",
    keywords: ["recommendation", "deadline", "office hours"],
    questions: [
      {
        promptEn: "Your classmate needs a ___ letter.",
        correctWord: "recommendation",
        prefixLength: 3,
        coachTh: "จดหมายประเภทไหนที่ต้องเขียน? ขึ้นต้น rec",
        coachEn: "What kind of letter? Starts with rec.",
        explanationTh: "recommendation letter = จดหมายแนะนำตัว",
        explanationEn: "recommendation letter = letter supporting an application.",
      },
      {
        promptEn: "The graduate school ___ is next Friday.",
        correctWord: "deadline",
        prefixLength: 3,
        coachTh: "วันสุดท้ายส่งใบสมัครเรียกว่าอะไร? ขึ้นต้น dea",
        coachEn: "Last day to apply — starts with dea.",
        explanationTh: "deadline = กำหนดส่ง / เดดไลน์",
        explanationEn: "deadline = final submission date.",
      },
      {
        promptEn: "You visit the professor during ___ hours.",
        correctWord: "office",
        prefixLength: 2,
        coachTh: "เวลาที่อาจารย์รอรับนักศึกษาเรียกว่าอะไร? ขึ้นต้น of",
        coachEn: "Professor's open hours — starts with of.",
        explanationTh: "office hours = เวลา office hour ของอาจารย์",
        explanationEn: "office hours = scheduled time professors meet students.",
      },
    ],
  },
  {
    id: "03",
    titleTh: "อ่าน syllabus",
    titleEn: "Reading the syllabus",
    scenarioEn:
      "On the first day of class, your professor walks through the syllabus and reminds everyone that the first major assignment is due in two weeks.",
    keywords: ["syllabus", "assignment", "professor"],
    questions: [
      {
        promptEn: "The professor reviews the course ___.",
        correctWord: "syllabus",
        prefixLength: 3,
        coachTh: "เอกสารรายละเอียดวิชาเรียกว่าอะไร? ขึ้นต้น syl",
        coachEn: "Course outline document — starts with syl.",
        explanationTh: "syllabus = โครงร่างวิชา / ใบปะหน้าวิชา",
        explanationEn: "syllabus = official course outline.",
      },
      {
        promptEn: "A major ___ is due in two weeks.",
        correctWord: "assignment",
        prefixLength: 3,
        coachTh: "งานที่ต้องส่งเรียกว่าอะไร? ขึ้นต้น ass",
        coachEn: "Homework task — starts with ass.",
        explanationTh: "assignment = งานที่อาจารย์มอบหมาย",
        explanationEn: "assignment = graded coursework task.",
      },
      {
        promptEn: "It is the first day of ___.",
        correctWord: "class",
        prefixLength: 2,
        coachTh: "วันแรกของอะไร? ขึ้นต้น cl",
        coachEn: "First day of what? Starts with cl.",
        explanationTh: "class = คาบเรียน / วิชาเรียน",
        explanationEn: "class = the course session.",
      },
    ],
  },
  {
    id: "04",
    titleTh: "ขอทุนการศึกษา",
    titleEn: "Scholarship application",
    scenarioEn:
      "You visit the financial aid office because your tuition increased. The counselor explains which scholarship forms you must submit before the semester starts.",
    keywords: ["financial aid", "tuition", "scholarship"],
    questions: [
      {
        promptEn: "You visit the ___ aid office.",
        correctWord: "financial",
        prefixLength: 3,
        coachTh: "หน่วยงานช่วยเรื่องเงินเรียกว่าอะไร? ขึ้นต้น fin",
        coachEn: "Money-help office — starts with fin.",
        explanationTh: "financial aid = งานการเงิน/ทุนการศึกษา",
        explanationEn: "financial aid = office handling student funding.",
      },
      {
        promptEn: "Your ___ went up this year.",
        correctWord: "tuition",
        prefixLength: 3,
        coachTh: "ค่าเทอมภาษาอังกฤษคืออะไร? ขึ้นต้น tui",
        coachEn: "School fee — starts with tui.",
        explanationTh: "tuition = ค่าเล่าเรียน / ค่าเทอม",
        explanationEn: "tuition = cost of attending college.",
      },
      {
        promptEn: "You need a ___ form.",
        correctWord: "scholarship",
        prefixLength: 3,
        coachTh: "แบบฟอร์มทุนเรียกว่าอะไร? ขึ้นต้น sch",
        coachEn: "Grant application — starts with sch.",
        explanationTh: "scholarship = ทุนการศึกษา",
        explanationEn: "scholarship = merit or need-based grant.",
      },
    ],
  },
  {
    id: "05",
    titleTh: "เพื่อนร่วมห้อง",
    titleEn: "Dorm roommate",
    scenarioEn:
      "Your new roommate in the dorm says the laundry room closes at ten, and asks you to split the cost of a mini-fridge for the room.",
    keywords: ["roommate", "dormitory", "laundry"],
    questions: [
      {
        promptEn: "You have a new ___ in the dorm.",
        correctWord: "roommate",
        prefixLength: 3,
        coachTh: "คนอยู่ห้องด้วยเรียกว่าอะไร? ขึ้นต้น roo",
        coachEn: "Person sharing your room — starts with roo.",
        explanationTh: "roommate = เพื่อนร่วมห้อง",
        explanationEn: "roommate = person you share housing with.",
      },
      {
        promptEn: "The ___ room closes at ten.",
        correctWord: "laundry",
        prefixLength: 3,
        coachTh: "ห้องซักผ้าเรียกว่าอะไร? ขึ้นต้น lau",
        coachEn: "Washing room — starts with lau.",
        explanationTh: "laundry room = ห้องซักผ้าในหอพัก",
        explanationEn: "laundry room = dorm washing facility.",
      },
      {
        promptEn: "You live in a ___.",
        correctWord: "dormitory",
        prefixLength: 2,
        coachTh: "หอพักนักศึกษา — ขึ้นต้น do",
        coachEn: "Student housing — starts with do.",
        explanationTh: "dormitory (dorm) = หอพักนักศึกษา",
        explanationEn: "dormitory = on-campus student housing.",
      },
    ],
  },
  {
    id: "06",
    titleTh: "สมัครฝึกงาน",
    titleEn: "Internship interview",
    scenarioEn:
      "At the career center, an advisor reviews your resume and schedules a mock interview for the summer internship you found on the campus job board.",
    keywords: ["internship", "resume", "interview"],
    questions: [
      {
        promptEn: "You apply for a summer ___.",
        correctWord: "internship",
        prefixLength: 3,
        coachTh: "การฝึกงานเรียกว่าอะไร? ขึ้นต้น int",
        coachEn: "Work placement — starts with int.",
        explanationTh: "internship = การฝึกงาน / สหกิจ",
        explanationEn: "internship = short-term work experience.",
      },
      {
        promptEn: "The advisor checks your ___.",
        correctWord: "resume",
        prefixLength: 3,
        coachTh: "ประวัติย่อภาษาอังกฤษคืออะไร? ขึ้นต้น res",
        coachEn: "CV document — starts with res.",
        explanationTh: "resume = เรซูเม่ / ประวัติย่อ",
        explanationEn: "resume = summary of education and experience.",
      },
      {
        promptEn: "They schedule a mock ___.",
        correctWord: "interview",
        prefixLength: 3,
        coachTh: "การสัมภาษณ์ — ขึ้นต้น int",
        coachEn: "Job meeting — starts with int.",
        explanationTh: "interview = การสัมภาษณ์งาน",
        explanationEn: "interview = formal meeting with an employer.",
      },
    ],
  },
  {
    id: "07",
    titleTh: "ปรึกษาอาจารย์ที่ปรึกษา",
    titleEn: "Thesis advisor",
    scenarioEn:
      "Your thesis advisor says your research proposal needs a clearer hypothesis before you can register for the independent study credit.",
    keywords: ["thesis", "advisor", "hypothesis"],
    questions: [
      {
        promptEn: "You work on your senior ___.",
        correctWord: "thesis",
        prefixLength: 3,
        coachTh: "วิทยานิพนธ์/โปรเจกต์จบ — ขึ้นต้น the",
        coachEn: "Final research paper — starts with the.",
        explanationTh: "thesis = วิทยานิพนธ์ / งานวิจัยจบ",
        explanationEn: "thesis = major research project for graduation.",
      },
      {
        promptEn: "Your ___ reviews the proposal.",
        correctWord: "advisor",
        prefixLength: 2,
        coachTh: "อาจารย์ที่ปรึกษา — ขึ้นต้น ad",
        coachEn: "Faculty mentor — starts with ad.",
        explanationTh: "advisor = อาจารย์ที่ปรึกษาวิทยานิพนธ์",
        explanationEn: "advisor = faculty supervisor for your thesis.",
      },
      {
        promptEn: "You need a clearer ___.",
        correctWord: "hypothesis",
        prefixLength: 3,
        coachTh: "ข้อสมมติฐานในงานวิจัย — ขึ้นต้น hyp",
        coachEn: "Research guess to test — starts with hyp.",
        explanationTh: "hypothesis = สมมติฐาน",
        explanationEn: "hypothesis = testable prediction in research.",
      },
    ],
  },
  {
    id: "08",
    titleTh: "โปรเจกต์กลุ่ม",
    titleEn: "Group presentation",
    scenarioEn:
      "Your team meets in the library to prepare a group presentation. One classmate volunteers to create the slides while you handle the research citations.",
    keywords: ["presentation", "collaborate", "citation"],
    questions: [
      {
        promptEn: "You prepare a group ___.",
        correctWord: "presentation",
        prefixLength: 3,
        coachTh: "การนำเสนอหน้าชั้น — ขึ้นต้น pre",
        coachEn: "Class talk with slides — starts with pre.",
        explanationTh: "presentation = การนำเสนอ",
        explanationEn: "presentation = formal talk to the class.",
      },
      {
        promptEn: "You must ___ on the project.",
        correctWord: "collaborate",
        prefixLength: 3,
        coachTh: "ทำงานร่วมกัน — ขึ้นต้น col",
        coachEn: "Work together — starts with col.",
        explanationTh: "collaborate = ร่วมมือ / ทำงานเป็นทีม",
        explanationEn: "collaborate = work jointly with others.",
      },
      {
        promptEn: "You check every ___ carefully.",
        correctWord: "citation",
        prefixLength: 3,
        coachTh: "การอ้างอิงแหล่งที่มา — ขึ้นต้น cit",
        coachEn: "Source reference — starts with cit.",
        explanationTh: "citation = การอ้างอิง / citation",
        explanationEn: "citation = formal reference to a source.",
      },
    ],
  },
  {
    id: "09",
    titleTh: "หนังสือค้างคืน",
    titleEn: "Overdue library book",
    scenarioEn:
      "The librarian emails you that a reserved textbook is overdue. You apologize and ask if you can renew it online for one more week.",
    keywords: ["reserve", "overdue", "renew"],
    questions: [
      {
        promptEn: "You had a ___ textbook.",
        correctWord: "reserved",
        prefixLength: 3,
        coachTh: "หนังสือที่จองไว้ — ขึ้นต้น res",
        coachEn: "Book held for you — starts with res.",
        explanationTh: "reserved = จองไว้ล่วงหน้า",
        explanationEn: "reserved = booked in advance at the library.",
      },
      {
        promptEn: "The book is ___.",
        correctWord: "overdue",
        prefixLength: 3,
        coachTh: "เลยกำหนดคืน — ขึ้นต้น ove",
        coachEn: "Past return date — starts with ove.",
        explanationTh: "overdue = เกินกำหนดคืน",
        explanationEn: "overdue = returned later than the due date.",
      },
      {
        promptEn: "You want to ___ it online.",
        correctWord: "renew",
        prefixLength: 2,
        coachTh: "ยืมต่อ — ขึ้นต้น re",
        coachEn: "Borrow again — starts with re.",
        explanationTh: "renew = ต่ออายุการยืม",
        explanationEn: "renew = extend the borrowing period.",
      },
    ],
  },
  {
    id: "10",
    titleTh: "เกรดตก",
    titleEn: "Academic probation",
    scenarioEn:
      "After midterms, your GPA dropped below the requirement. Academic counseling invites you to a workshop on study strategies and time management.",
    keywords: ["probation", "GPA", "counseling"],
    questions: [
      {
        promptEn: "You are on academic ___.",
        correctWord: "probation",
        prefixLength: 3,
        coachTh: "ภาวะทดลองเรียนเมื่อเกรดต่ำ — ขึ้นต้น pro",
        coachEn: "Warning status for low grades — starts with pro.",
        explanationTh: "academic probation = อยู่ในภาวะทดลองเรียน",
        explanationEn: "academic probation = formal warning for poor grades.",
      },
      {
        promptEn: "Your ___ fell below the requirement.",
        correctWord: "GPA",
        prefixLength: 1,
        coachTh: "เกรดเฉลี่ยย่อ — ขึ้นต้น G",
        coachEn: "Grade point average — starts with G.",
        explanationTh: "GPA = Grade Point Average เกรดเฉลี่ย",
        explanationEn: "GPA = grade point average.",
      },
      {
        promptEn: "You attend a ___ workshop.",
        correctWord: "counseling",
        prefixLength: 3,
        coachTh: "งานให้คำปรึกษา — ขึ้นต้น cou",
        coachEn: "Guidance session — starts with cou.",
        explanationTh: "counseling = การให้คำปรึกษา",
        explanationEn: "counseling = professional academic guidance.",
      },
    ],
  },
  {
    id: "11",
    titleTh: "แลกเปลี่ยนต่างประเทศ",
    titleEn: "Study abroad",
    scenarioEn:
      "Your classmate just returned from a study abroad program in Spain. She explains how she got her visa approved before the exchange semester began.",
    keywords: ["exchange", "visa", "semester"],
    questions: [
      {
        promptEn: "She joined an ___ program.",
        correctWord: "exchange",
        prefixLength: 3,
        coachTh: "โครงการแลกเปลี่ยน — ขึ้นต้น exc",
        coachEn: "Swap schools program — starts with exc.",
        explanationTh: "exchange program = โครงการแลกเปลี่ยนนักศึกษา",
        explanationEn: "exchange program = study at a partner university.",
      },
      {
        promptEn: "She needed a student ___.",
        correctWord: "visa",
        prefixLength: 2,
        coachTh: "เอกสารเข้าประเทศ — ขึ้นต้น vi",
        coachEn: "Travel permit — starts with vi.",
        explanationTh: "visa = วีซ่า",
        explanationEn: "visa = official permission to enter a country.",
      },
      {
        promptEn: "It lasted one ___.",
        correctWord: "semester",
        prefixLength: 3,
        coachTh: "ภาคเรียน — ขึ้นต้น sem",
        coachEn: "Half-year term — starts with sem.",
        explanationTh: "semester = ภาคเรียน",
        explanationEn: "semester = half of the academic year.",
      },
    ],
  },
  {
    id: "12",
    titleTh: "รายงานแล็บ",
    titleEn: "Lab report",
    scenarioEn:
      "In chemistry lab, your partner suggests changing the experiment procedure. Your TA reminds you to write a conclusion that matches your data table.",
    keywords: ["experiment", "procedure", "conclusion"],
    questions: [
      {
        promptEn: "You run an ___ in lab.",
        correctWord: "experiment",
        prefixLength: 3,
        coachTh: "การทดลอง — ขึ้นต้น exp",
        coachEn: "Scientific test — starts with exp.",
        explanationTh: "experiment = การทดลอง",
        explanationEn: "experiment = controlled scientific test.",
      },
      {
        promptEn: "You may change the ___.",
        correctWord: "procedure",
        prefixLength: 3,
        coachTh: "ขั้นตอนการทำ — ขึ้นต้น pro",
        coachEn: "Step-by-step method — starts with pro.",
        explanationTh: "procedure = ขั้นตอนวิธีการ",
        explanationEn: "procedure = ordered steps of the lab work.",
      },
      {
        promptEn: "The report needs a clear ___.",
        correctWord: "conclusion",
        prefixLength: 3,
        coachTh: "บทสรุป — ขึ้นต้น con",
        coachEn: "Final summary — starts with con.",
        explanationTh: "conclusion = สรุปผล / ข้อสรุป",
        explanationEn: "conclusion = final interpretation of results.",
      },
    ],
  },
  {
    id: "13",
    titleTh: "เทียบโอนหน่วยกิต",
    titleEn: "Transfer credits",
    scenarioEn:
      "You meet the registrar to transfer credits from community college. She asks for an official transcript to see which courses are equivalent here.",
    keywords: ["transfer", "transcript", "equivalent"],
    questions: [
      {
        promptEn: "You want to ___ credits.",
        correctWord: "transfer",
        prefixLength: 3,
        coachTh: "ย้ายหน่วยกิต — ขึ้นต้น tra",
        coachEn: "Move units — starts with tra.",
        explanationTh: "transfer credits = เทียบโอนหน่วยกิต",
        explanationEn: "transfer credits = count prior coursework here.",
      },
      {
        promptEn: "Bring an official ___.",
        correctWord: "transcript",
        prefixLength: 3,
        coachTh: "ใบแสดงผลการเรียน — ขึ้นต้น tra",
        coachEn: "Grade record — starts with tra.",
        explanationTh: "transcript = transcript / ใบรายงานผล",
        explanationEn: "transcript = official academic record.",
      },
      {
        promptEn: "Check which courses are ___.",
        correctWord: "equivalent",
        prefixLength: 3,
        coachTh: "เทียบเท่า — ขึ้นต้น equ",
        coachEn: "Same value — starts with equ.",
        explanationTh: "equivalent = เทียบเท่า / นับแทนได้",
        explanationEn: "equivalent = accepted as the same requirement.",
      },
    ],
  },
  {
    id: "14",
    titleTh: "ชมรมในมหาวิทยาลัย",
    titleEn: "Campus club",
    scenarioEn:
      "At the student club fair, the treasurer of the debate club explains the membership fee and invites you to the first meeting next Tuesday.",
    keywords: ["membership", "treasurer", "meeting"],
    questions: [
      {
        promptEn: "You pay a ___ fee.",
        correctWord: "membership",
        prefixLength: 3,
        coachTh: "ค่าสมาชิก — ขึ้นต้น mem",
        coachEn: "Joining cost — starts with mem.",
        explanationTh: "membership fee = ค่าธรรมเนียมสมาชิก",
        explanationEn: "membership fee = cost to join the club.",
      },
      {
        promptEn: "Talk to the club ___.",
        correctWord: "treasurer",
        prefixLength: 3,
        coachTh: "เหรัญญิกชมรม — ขึ้นต้น tre",
        coachEn: "Money officer — starts with tre.",
        explanationTh: "treasurer = เหรัญญิก",
        explanationEn: "treasurer = officer who manages club funds.",
      },
      {
        promptEn: "Come to the first ___.",
        correctWord: "meeting",
        prefixLength: 3,
        coachTh: "การประชุม — ขึ้นต้น mee",
        coachEn: "Gathering — starts with mee.",
        explanationTh: "meeting = การประชุม",
        explanationEn: "meeting = scheduled club gathering.",
      },
    ],
  },
  {
    id: "15",
    titleTh: "ลงทะเบียนเรียน",
    titleEn: "Course enrollment",
    scenarioEn:
      "You cannot enroll in advanced statistics because you lack the prerequisite. The registrar suggests taking an introductory section instead or waiting until next term.",
    keywords: ["enrollment", "prerequisite", "registrar"],
    questions: [
      {
        promptEn: "Your ___ is blocked.",
        correctWord: "enrollment",
        prefixLength: 3,
        coachTh: "การลงทะเบียน — ขึ้นต้น enr",
        coachEn: "Signing up for class — starts with enr.",
        explanationTh: "enrollment = การลงทะเบียนเรียน",
        explanationEn: "enrollment = official registration in a course.",
      },
      {
        promptEn: "You miss a ___.",
        correctWord: "prerequisite",
        prefixLength: 3,
        coachTh: "วิชาที่ต้องเรียนมาก่อน — ขึ้นต้น pre",
        coachEn: "Required prior course — starts with pre.",
        explanationTh: "prerequisite = วิชาบังคับก่อน",
        explanationEn: "prerequisite = course you must take first.",
      },
      {
        promptEn: "Ask the ___.",
        correctWord: "registrar",
        prefixLength: 3,
        coachTh: "งานทะเบียน — ขึ้นต้น reg",
        coachEn: "Records office — starts with reg.",
        explanationTh: "registrar = สำนักทะเบียน / งานทะเบียน",
        explanationEn: "registrar = office managing student records.",
      },
    ],
  },
  {
    id: "16",
    titleTh: "แพ็กอาหาร",
    titleEn: "Meal plan",
    scenarioEn:
      "In the cafeteria, your roommate complains that the vegetarian options are limited. You compare meal plans to see which one fits your weekly budget.",
    keywords: ["cafeteria", "vegetarian", "budget"],
    questions: [
      {
        promptEn: "You eat in the ___.",
        correctWord: "cafeteria",
        prefixLength: 3,
        coachTh: "โรงอาหารในมหาลัย — ขึ้นต้น caf",
        coachEn: "Campus dining hall — starts with caf.",
        explanationTh: "cafeteria = โรงอาหาร / โรงอาหารนักศึกษา",
        explanationEn: "cafeteria = campus dining hall.",
      },
      {
        promptEn: "You want more ___ meals.",
        correctWord: "vegetarian",
        prefixLength: 3,
        coachTh: "มังสวิรัติ — ขึ้นต้น veg",
        coachEn: "Plant-based food — starts with veg.",
        explanationTh: "vegetarian = อาหารมังสวิรัติ",
        explanationEn: "vegetarian = meals without meat.",
      },
      {
        promptEn: "Pick a plan that fits your ___.",
        correctWord: "budget",
        prefixLength: 2,
        coachTh: "งบประมาณ — ขึ้นต้น bu",
        coachEn: "Money limit — starts with bu.",
        explanationTh: "budget = งบประมาณ",
        explanationEn: "budget = amount you can afford to spend.",
      },
    ],
  },
  {
    id: "17",
    titleTh: "ถาม TA",
    titleEn: "TA office hours",
    scenarioEn:
      "After a confusing lecture, you visit your teaching assistant during supplemental instruction. The TA walks you through the homework problems step by step.",
    keywords: ["tutoring", "lecture", "homework"],
    questions: [
      {
        promptEn: "The TA offers ___ help.",
        correctWord: "tutoring",
        prefixLength: 3,
        coachTh: "ติวเสริม — ขึ้นต้น tut",
        coachEn: "Extra teaching — starts with tut.",
        explanationTh: "tutoring = การติว / สอนเสริม",
        explanationEn: "tutoring = one-on-one academic help.",
      },
      {
        promptEn: "The ___ was confusing.",
        correctWord: "lecture",
        prefixLength: 3,
        coachTh: "บรรยาย — ขึ้นต้น lec",
        coachEn: "Class talk — starts with lec.",
        explanationTh: "lecture = การบรรยาย",
        explanationEn: "lecture = professor's classroom presentation.",
      },
      {
        promptEn: "You review the ___ problems.",
        correctWord: "homework",
        prefixLength: 3,
        coachTh: "การบ้าน — ขึ้นต้น hom",
        coachEn: "Take-home work — starts with hom.",
        explanationTh: "homework = การบ้าน",
        explanationEn: "homework = assignments done outside class.",
      },
    ],
  },
  {
    id: "18",
    titleTh: "เกียรตินิยม",
    titleEn: "Dean's list",
    scenarioEn:
      "Your professor congratulates you for making the dean's list this semester. She says the honors certificate will be mailed after commencement rehearsal.",
    keywords: ["honors", "commencement", "certificate"],
    questions: [
      {
        promptEn: "You made the dean's ___.",
        correctWord: "list",
        prefixLength: 2,
        coachTh: "รายชื่อเกียรตินิยม — ขึ้นต้น li",
        coachEn: "Honor roll — last word starts with li.",
        explanationTh: "dean's list = รายชื่อนักศึกษาเกียรตินิยม",
        explanationEn: "dean's list = honor roll for high GPA.",
      },
      {
        promptEn: "You receive an ___ certificate.",
        correctWord: "honors",
        prefixLength: 2,
        coachTh: "เกียรตินิยม — ขึ้นต้น ho",
        coachEn: "Academic distinction — starts with ho.",
        explanationTh: "honors = เกียรตินิยม",
        explanationEn: "honors = formal academic recognition.",
      },
      {
        promptEn: "It arrives after ___ rehearsal.",
        correctWord: "commencement",
        prefixLength: 3,
        coachTh: "พิธีจบการศึกษา — ขึ้นต้น com",
        coachEn: "Graduation ceremony — starts with com.",
        explanationTh: "commencement = พิธีรับปริญญา",
        explanationEn: "commencement = graduation ceremony.",
      },
    ],
  },
  {
    id: "19",
    titleTh: "นโยบายคัดลอกงาน",
    titleEn: "Plagiarism policy",
    scenarioEn:
      "Your professor warns the class about plagiarism on the final essay. You must cite every source and paraphrase ideas in your own words.",
    keywords: ["plagiarism", "citation", "paraphrase"],
    questions: [
      {
        promptEn: "The professor warns about ___.",
        correctWord: "plagiarism",
        prefixLength: 3,
        coachTh: "การลอกเลียนแบบ — ขึ้นต้น pla",
        coachEn: "Copying without credit — starts with pla.",
        explanationTh: "plagiarism = การลอกผลงาน",
        explanationEn: "plagiarism = using others' work without credit.",
      },
      {
        promptEn: "Include a proper ___.",
        correctWord: "citation",
        prefixLength: 3,
        coachTh: "การอ้างอิง — ขึ้นต้น cit",
        coachEn: "Source note — starts with cit.",
        explanationTh: "citation = การอ้างอิงแหล่งที่มา",
        explanationEn: "citation = reference to the original source.",
      },
      {
        promptEn: "You should ___ the ideas.",
        correctWord: "paraphrase",
        prefixLength: 3,
        coachTh: "ถอดความด้วยคำพูดตัวเอง — ขึ้นต้น par",
        coachEn: "Rewrite in your words — starts with par.",
        explanationTh: "paraphrase = ถอดความใหม่",
        explanationEn: "paraphrase = express ideas in your own words.",
      },
    ],
  },
  {
    id: "20",
    titleTh: "โปรเจกต์จบ",
    titleEn: "Capstone project",
    scenarioEn:
      "In your final year, your capstone team presents to faculty judges. After passing the defense, you will receive your diploma at graduation.",
    keywords: ["capstone", "diploma", "graduation"],
    questions: [
      {
        promptEn: "You complete a ___ project.",
        correctWord: "capstone",
        prefixLength: 3,
        coachTh: "โปรเจกต์บูรณาการปีสุดท้าย — ขึ้นต้น cap",
        coachEn: "Final-year project — starts with cap.",
        explanationTh: "capstone = โปรเจกต์สรุปหลักสูตร",
        explanationEn: "capstone = culminating senior project.",
      },
      {
        promptEn: "You pass the project ___.",
        correctWord: "defense",
        prefixLength: 3,
        coachTh: "การสอบปากเปล่า — ขึ้นต้น def",
        coachEn: "Oral exam — starts with def.",
        explanationTh: "defense = การนำเสนอและสอบโปรเจกต์",
        explanationEn: "defense = formal presentation to faculty.",
      },
      {
        promptEn: "You receive your ___.",
        correctWord: "diploma",
        prefixLength: 3,
        coachTh: "ประกาศนียบัตร — ขึ้นต้น dip",
        coachEn: "Degree document — starts with dip.",
        explanationTh: "diploma = ประกาศนียบัตร / ใบปริญญา",
        explanationEn: "diploma = official graduation certificate.",
      },
    ],
  },
];

export function getCampusScenario(id: string): CampusListeningScenario | undefined {
  return CAMPUS_LISTENING_SCENARIOS.find((s) => s.id === id);
}
