export const INTERACTIVE_SPEAKING_FOLLOWUP_COUNT = 5;
export const INTERACTIVE_SPEAKING_TURN_COUNT = 1 + INTERACTIVE_SPEAKING_FOLLOWUP_COUNT;
export const INTERACTIVE_SPEAKING_PREP_SECONDS = 3;
export const INTERACTIVE_SPEAKING_MAX_SPEAK_SECONDS = 35;
